app/models/__init__.py
"""Models package"""

app/models/machine.py
from app.extensions import db

class Machine(db.Model):
    __tablename__ = 'machine'

    id = db.Column(db.Integer(), primary_key=True)
    label = db.Column(db.String(80), unique=True, nullable=False)

    server_id = db.Column(db.Integer, db.ForeignKey('server.id'), nullable=False)
    server = db.relationship('Server', backref=db.backref('machines', lazy=True))

    def __repr__(self):
        return "<Machine: {}>".format(self.label)

app/models/server.py
from app.extensions import db
from datetime import datetime

class Server(db.Model):
    __tablename__ = 'server'

    id = db.Column(db.Integer(), primary_key=True)
    url = db.Column(db.Integer(), unique=True, nullable=False)
    timestamp = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    def __repr__(self):
        return "<Server: {}>".format(self.url)

app/models/status.py
from app.extensions import db
from datetime import datetime

class Status(db.Model):
    __tablename__ = 'status'

    id = db.Column(db.Integer(), primary_key=True)

    description = db.Column(db.Text, nullable=False)
    timestamp = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    machine_id = db.Column(db.Integer, db.ForeignKey('machine.id'), nullable=False)
    machine = db.relationship('Machine', backref=db.backref('statuses', lazy=True))

    def __repr__(self):
        return "<Status: {} - {}>".format(self.machine.label, self.timestamp)

app/__init__.py
"""Main application package"""

app/app.py
import os

from flask import Flask, render_template
from . import settings, controllers, models
from .extensions import db

project_dir = os.path.dirname(os.path.abspath(__file__))

def create_app(config_object=settings):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config_object)

    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app

def register_extensions(app):
    """Register Flask extensions."""
    db.init_app(app)

    with app.app_context():
        db.create_all()
    return None

def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(controllers.home.blueprint)
    app.register_blueprint(controllers.server.blueprint)
    app.register_blueprint(controllers.machine.blueprint)
    app.register_blueprint(controllers.status.blueprint)
    return None

def register_errorhandlers(app):
    """Register error handlers."""
    @app.errorhandler(401)
    def internal_error(error):
        return render_template('401.html'), 401

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('404.html'), 404

    @app.errorhandler(500)
    def internal_error(error):
        return render_template('500.html'), 500

    return None

app/controllers/__init__.py
"""Controllers package"""
from . import home
from . import server
from . import machine
from . import status

app/controllers/home.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

blueprint = Blueprint('home', __name__)

@blueprint.route('/')
def index():
    return render_template('home/index.html')

app/controllers/machine.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

from app.models.machine import Machine

blueprint = Blueprint('machine', __name__)

@blueprint.route('/machine')
def machine():
    return render_template('home/index.html')

app/controllers/server.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

from app.models.server import Server

blueprint = Blueprint('server', __name__)

@blueprint.route('/server')
def server():
    return render_template('home/index.html')

app/controllers/status.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

from app.models.status import Status

blueprint = Blueprint('status', __name__)

@blueprint.route('/status')
def status():
    return render_template('home/index.html')

app/services/__init__.py
"""Services package"""

app/templates/401.html
{% extends "layouts/layout.html" %}

{% block content %}
  <div class="container py-5 my-5 text-muted text-center">
    <h1 class="h5">This isn't the page you are looking for.</h1>
    <p>We couldn't find this page. Please check your URL or go back home.<p>
    <a href="/" class="btn btn-primary">Go back home</a>
  </div>
{% endblock %}

app/templates/home/index.html
{% extends "layouts/layout.html" %}

{% block header %}
<div class="bg-gray-light border-bottom border-gray-light">
  <div class="container text-center py-5 mb-4">
    <img src="{{ url_for('static', filename='img/logo.png') }}" class="w-100" style="max-width:120px;" />
    <div class="mt-3 mb-4">
      <h1 class="h1 mb-0">Hackathon Flask Starter</h1>
      <h2 class="h4 text-gray font-weight-light">Build your hackathon project faster.</h2>
    </div>
    <a class="btn btn-primary mt-2" href="https://github.com/MLH/mlh-hackathon-flask-starter">
      Check the Docs
    </a>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="text-gray-light text-center py-5 my-5">
  <p class="lead">Edit <code>controllers/</code> to update how to receive and reply to requests.</p>
  <p class="lead">Edit <code>templates/</code> to update the layout and styling.</p>
  <p class="lead">Edit <code>models/</code> to update how the data is stored.</p>
</div>
{% endblock %}

app/templates/layouts/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>My Hackathon Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" >
    <link rel="stylesheet" href="{{ url_for('static', filename='css/colors.css') }}" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  </head>
  <body>
    {% include "partials/header.html" %}

    {% include "partials/flash.html" %}

    {% block header %}{% endblock %}

    {% block content %}{% endblock %}

    {% include "partials/footer.html" %}

    <!-- Scripts for Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/templates/partials/flash.html
{% for category, message in get_flashed_messages(with_categories=true) %}
  <div class="alert alert-{{ category if category != None else 'danger' }} mb-0 rounded-0">
    <div class="container">
      {{ message }}
    </div>
  </div>
{% endfor %}

app/templates/partials/footer.html
{% block footer %}
  {# Add a global footer here if you like #}
{% endblock %}

app/templates/partials/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-gray-dark text-white">
  <div class="container">
    <a class="text-white link-reset text-inherit pr-3" href="/">
      ComputerCraft Remote Dash
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Tutorials
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ url_for('home.index' )}}">Requesting Data</a>
          </div>
        </li>
        {% if g.user %}
          <li class="nav-item p-2 pr-3">
            <img src="{{ g.user['avatar_url'] }}" class='rounded mr-2' style='width:24px;height:24px;'/>
            {{ g.user['username'] }}
          </li>
          <li class="nav-item">
            <a class="nav-link text-inherit" href="{{ url_for('home.index') }}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link text-inherit" href="{{ url_for('home.index') }}">
              Login with GitHub
            </a>
          </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>